repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: flake8
    -   id: check-added-large-files
    -   id: check-byte-order-marker
-   repo: git@github.com:asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: git@github.com:asottile/pyupgrade
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
